# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx3G -XX:+UseG1GC

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.251
neo_version_range=[21.1,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

version=1.21.1-1.0.4.2
curios_version=9.5.1+1.21.1
geckolib_version=4.9.3
tridot_version=1.0.170
tridot_version_range=[1.21.1-1.0.170,)

jei_version=19.57.0.447
jade_version=15.10.6+neoforge
kubejs_version=2101.7.2-build.377
rhino_version=2101.2.8-build.91
architectury_version=13.0.11
dummmmmmy_version=DldwQTMc
moonlight_version=HTfE7eCk
jer_version=TgNFki8j
