package com.idark.valoria.client.render.model.animations;

import net.minecraft.client.animation.*;
import net.minecraft.client.animation.AnimationChannel.*;

public class GoblinAnimations{
    public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(2.00f).looping()
    .addAnimation("head",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(0.50f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
    Interpolations.LINEAR),
    new Keyframe(1.00f, KeyframeAnimations.posVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(1.50f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
    Interpolations.LINEAR),
    new Keyframe(2.00f, KeyframeAnimations.posVec(0f, 0f, 0f),
    Interpolations.LINEAR)))
    .addAnimation("head",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.50f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.00f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.50f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(2.00f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("body",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(0.50f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
    Interpolations.LINEAR),
    new Keyframe(1.00f, KeyframeAnimations.posVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(1.50f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
    Interpolations.LINEAR),
    new Keyframe(2.00f, KeyframeAnimations.posVec(0f, 0f, 0f),
    Interpolations.LINEAR)))
    .addAnimation("body",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.50f, KeyframeAnimations.degreeVec(0f, 0f, -0.5f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.00f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.50f, KeyframeAnimations.degreeVec(0f, 0f, 0.5f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(2.00f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("right_arm",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.50f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.00f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.50f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(2.00f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("right_arm",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(0.50f, KeyframeAnimations.degreeVec(-8f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(1.00f, KeyframeAnimations.degreeVec(0, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(1.50f, KeyframeAnimations.degreeVec(8f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(2.00f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR)))
    .addAnimation("left_arm",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.50f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.00f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.50f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(2.00f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("left_arm",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(0.50f, KeyframeAnimations.degreeVec(8f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(1.00f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(1.50f, KeyframeAnimations.degreeVec(-8f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(2.00f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR))).build();

    public static final AnimationDefinition WALK = AnimationDefinition.Builder.withLength(2f).looping()
    .addAnimation("head",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.5f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("body",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.5f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("right_arm",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -0.75f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -0.75f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0.5f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, -0.75f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("right_arm",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.5f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(2f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("left_arm",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, -1f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, -0.75f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("left_arm",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.5f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(2f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("right_leg",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -1.5f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 1.5f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -1.5f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 1.5f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, -1.5f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("right_leg",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.5f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(2f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("left_leg",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 1.5f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, -1.5f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 1.5f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, -1.5f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 1.5f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("left_leg",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.5f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(2f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM))).build();

    public static final AnimationDefinition RUN = AnimationDefinition.Builder.withLength(1f).looping()
    .addAnimation("head",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, -1f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, -1f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("head",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.25f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.75f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("body",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.25f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.75f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("right_arm",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -0.75f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, -0.75f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0.5f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -0.75f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("right_arm",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.25f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.75f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("left_arm",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, -1f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, -0.75f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("left_arm",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.25f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.75f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("right_leg",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -2f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 2f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, -2f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 2f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -2f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("right_leg",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.25f, KeyframeAnimations.degreeVec(32.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.75f, KeyframeAnimations.degreeVec(32.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("left_leg",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 2f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, -2f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 2f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, -2f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 2f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("left_leg",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(32.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.25f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(32.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.75f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1f, KeyframeAnimations.degreeVec(32.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM))).build();

    public static final AnimationDefinition ATTACK = AnimationDefinition.Builder.withLength(1.6766667f).looping()
    .addAnimation("head",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, -0.25f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, -1f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0f, -1f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.0834333f, KeyframeAnimations.posVec(0f, 0f, -1.75f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.2916767f, KeyframeAnimations.posVec(0f, 0f, -2.75f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.6766667f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("head",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(2.52f, -7.49f, -0.33f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, -15f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, -25f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, -22.5f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, -25f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(0f, -17.5f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(0f, -12.5f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.5f, KeyframeAnimations.degreeVec(2.52f, -7.49f, -0.33f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("body",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0.25f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -1.5f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.125f, KeyframeAnimations.posVec(0f, 0f, -2.5f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.6766667f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("body",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(5.12f, -12.45f, -1.11f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, -25f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, -25f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, -20f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.5f, KeyframeAnimations.degreeVec(5.12f, -12.45f, -1.11f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("right_arm",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -2f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 3f, -4f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 3.75f, -2f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 2.5f, -0.75f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 4.7f, 0.05f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.7916766f, KeyframeAnimations.posVec(-0.3f, 5f, -1.34f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.9167666f, KeyframeAnimations.posVec(-0.75f, 2.75f, 0.5f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.0834333f, KeyframeAnimations.posVec(-0.75f, 2.75f, -3.25f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.2916767f, KeyframeAnimations.posVec(-0.75f, 2.75f, -6.25f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 3.75f, -2f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.6766667f, KeyframeAnimations.posVec(0f, 0f, -2f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("right_arm",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-92.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-105f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-79.76f, -12.31f, -2.2f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-117.26f, -12.31f, -2.2f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.75f, KeyframeAnimations.degreeVec(-130.18f, -12.31f, -2.2f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(-95.63f, -32.65f, 7.3f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(-94.76f, -5.26f, 4.69f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(-94.76f, -5.26f, 4.69f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.5f, KeyframeAnimations.degreeVec(-105f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("left_arm",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, -0.25f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 0f, -1.28f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, -1f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.6766666f, KeyframeAnimations.posVec(1f, 0f, -2.75f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.75f, KeyframeAnimations.posVec(1f, 0f, -4.5f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.9167666f, KeyframeAnimations.posVec(1f, 2.75f, -4.5f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.0834333f, KeyframeAnimations.posVec(1f, 3f, -6f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.2916767f, KeyframeAnimations.posVec(3f, 3f, -6f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, -1.28f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.6766667f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("left_arm",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-40f, -10f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.75f, KeyframeAnimations.degreeVec(-35f, -10f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-95.91f, -24.92f, 4.09f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(-87.5f, -10f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(-86.44f, -38.71f, -1.88f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.5f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("right_leg",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, -1f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0.75f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.6766666f, KeyframeAnimations.posVec(-0.5f, 0f, 0.75f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1f, KeyframeAnimations.posVec(-0.5f, 0f, -1f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.125f, KeyframeAnimations.posVec(-0.5f, 0f, -3f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.6766667f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("right_leg",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-5.31f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-0.14f, -34.05f, 8.62f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.125f, KeyframeAnimations.degreeVec(-12.64f, -34.05f, 8.62f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.5f, KeyframeAnimations.degreeVec(-5.31f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("left_leg",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0f, 0.25f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 0f, -0.75f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -1.5f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.6766667f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("left_leg",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(7.81f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.5f, KeyframeAnimations.degreeVec(7.81f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition ATTACK_WEAPON = AnimationDefinition.Builder.withLength(1f)
    .addAnimation("head",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0f, 0.25f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("head",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(0.125f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("body",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0f, 0.25f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("body",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.125f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.25f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("right_arm",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(0.4583433f, KeyframeAnimations.posVec(0f, 6f, -2f),
    Interpolations.LINEAR),
    new Keyframe(0.7916766f, KeyframeAnimations.posVec(0f, 6f, 2f),
    Interpolations.LINEAR),
    new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -2f),
    Interpolations.LINEAR)))
    .addAnimation("right_arm",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(-152.5f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(-222.5f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(1f, KeyframeAnimations.degreeVec(-40f, 0f, 0f),
    Interpolations.LINEAR)))
    .addAnimation("right_leg",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.125f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.25f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR))).build();
}