package com.idark.valoria.client.render.model.animations;

import net.minecraft.client.animation.*;
import net.minecraft.client.animation.AnimationChannel.*;

public class SuccubusAnimation{
    public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(1.75f).looping()
    .addAnimation("left_ear",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
    Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0.75f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
    Interpolations.LINEAR),
    new Keyframe(1.5416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR)))
    .addAnimation("right_ear",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
    Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0.75f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
    Interpolations.LINEAR),
    new Keyframe(1.5416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR)))
    .addAnimation("body",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(0.5f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
    new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
    .addAnimation("left_arm",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, -0.15f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("left_arm",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
    Interpolations.LINEAR),
    new Keyframe(1.125f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR)))
    .addAnimation("right_arm",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.5416766f, KeyframeAnimations.posVec(0f, -0.15f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("right_arm",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
    Interpolations.LINEAR),
    new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    Interpolations.LINEAR)))
    .addAnimation("left_wing",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, -10f, -0.45f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("right_wing",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 10f, -0.45f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM))).build();

    public static final AnimationDefinition ATTACK_RANGE = AnimationDefinition.Builder.withLength(1.25f)
    .addAnimation("head",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 0f, 2f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("head",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-7.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("leftEar",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 0f, 2f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("leftEar",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, -76.67f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("rightEar",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 0f, 2f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("rightEar",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, 76.67f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("body",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-7.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("leftArm",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    Interpolations.LINEAR),
    new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 7f, 3f),
    Interpolations.LINEAR),
    new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 4f, -5f),
    Interpolations.LINEAR),
    new Keyframe(1.125f, KeyframeAnimations.posVec(0f, 0f, 0f),
    Interpolations.LINEAR)))
    .addAnimation("leftArm",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.25f, KeyframeAnimations.degreeVec(-210f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-102.5f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.125f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("rightArm",
    new AnimationChannel(AnimationChannel.Targets.POSITION,
    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 0f, 2f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("rightArm",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.125f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("leftWing",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("rightWing",
    new AnimationChannel(AnimationChannel.Targets.ROTATION,
    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
    AnimationChannel.Interpolations.CATMULLROM),
    new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.CATMULLROM))).build();
}